os: osx
osx_image: xcode12.2
language: swift
script: xcodebuild clean build test -workspace QuizApp.xcworkspace/ -scheme "QuizEngine_iOS" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=14.5,name=iPhone 8" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
